//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoStudio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Service = new HashSet<Service>();
        }
    
        public int idOrder { get; set; }
        public System.DateTime ordDate { get; set; }
        public int idClient { get; set; }
        public Nullable<int> idEmployee { get; set; }
        public Nullable<int> idStudio { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Studio Studio { get; set; }
        public virtual Client Сlient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service> Service { get; set; }
    }
}
